- hosts: all
  become: true

  tasks:
    - name: Fix dns
      command: sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf 
    - name: Install aptitude
      retries: 3
      delay: 10
      package:
        name: aptitude
        state: present
    - name: Update apt cache
      command: aptitude update
      retries: 3
      delay: 10
