- hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      become: true 
      apt:
        upgrade: yes
        update_cache: yes
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=no force_apt_get=yes

